name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install vulkan tools
      run: sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils
    - name: vulkan sdk
      run: mkdir vulkan && cd vulkan && sudo curl -o VulkanSDK.tar.gz https://sdk.lunarg.com/sdk/download/1.2.148.0/linux/vulkansdk-linux-x86_64-1.2.148.0.tar.gz && sudo tar xf VulkanSDK.tar.gz 
    - name: ls
      run: ls
    - name: vulkan-info
      run: vulkan-info
      
    - uses: actions/checkout@v2
    - name: apt install packages
      run: sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: clone submodules
      run: git submodule update --init
    - name: cmake
      run: cmake . 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
