name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: vulkan sdk
      run: mkdir -p ~/vulkan/VulkanSDK && cd ~/vulkan/ && sudo curl -o vulkansdk-macos-1.2.141.2.dmg https://sdk.lunarg.com/sdk/download/1.2.141.2/mac/vulkansdk-macos-1.2.141.2.dmg && cd VulkanSDK && sudo hdiutil attach ../vulkansdk-macos-1.2.141.2.dmg && cd /Volumes/vulkansdk-macos-1.2.141.2/ && ./install_vulkan.py --force-install
    - uses: actions/checkout@v2
    - name: clone submodules
      run: git submodule update --recursive --init
    - name: cmake
      run: cmake . &&  cmake . 
    - name: make -j8
      run: make dreamroam
