name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup script parameters
      run: SCRIPT=$(readlink -f "$0") && SCRIPTPATH=$(dirname "$SCRIPT") && echo $SCRIPTPATH

    - name: install vulkan tools
      run: sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils
    - name: vulkan sdk
      run: mkdir -p /local/vulkan/VulkanSDK && cd /local/vulkan/ && sudo curl -o VulkanSDK.tar.gz https://sdk.lunarg.com/sdk/download/1.2.148.0/linux/vulkansdk-linux-x86_64-1.2.148.0.tar.gz && cd VulkanSDK && sudo tar xf ../VulkanSDK.tar.gz && cd $SCRIPTPATH 
    - name: source vulkan sdk
      run: export VULKAN_SDK="/local/vulkan/VulkanSDK/1.2.148.0/x86_64" && export PATH="${VULKAN_SDK}/bin:${PATH}" && export LD_LIBRARY_PATH="${VULKAN_SDK}/lib:${LD_LIBRARY_PATH}" && export VK_LAYER_PATH="${VULKAN_SDK}/etc/explicit_layer.d:${VK_LAYER_PATH}"
      
    - name: vulkan-info
      run: echo $PATH && vulkan-info
      
    - uses: actions/checkout@v2
    - name: apt install packages
      run: sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: clone submodules
      run: git submodule update --init
    - name: cmake
      run: cmake . 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
