name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install packages
      run: sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: clone submodules
      run: git submodule update --init
    - name: vulkan-info
      run: vulkan-info
    - name: cmake
      run: cmake . 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
