name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install packages
      uses: ryankurte/action-apt@v0.1.0
      with: 
        packages: "libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev"
    - name: cloneSubmodules
      run: git submodule update --init
    - name: cmake
      run: cmake . 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
